apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mg1z5qdci-go
  janus-idp.io/tekton: mg1z5qdci-go
  backstage.io/kubernetes-id: mg1z5qdci-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mg1z5qdci-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
